[package]
name = "derive_utils_codegen"
version = "0.1.0"
authors = ["Sergio Benitez <sb@sergio.bz>"]
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
derive_utils_core = { path = "../core/" }
