[package]
name = "devise_codegen"
version = "0.1.0"
authors = ["Sergio Benitez <sb@sergio.bz>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
devise_core = { version = "0.1", path = "../core/" }
