[package]
name = "devise_core"
version = "0.2.0"
authors = ["Sergio Benitez <sb@sergio.bz>"]
description = "A library for devising derives and other procedural macros."
license = "MIT/Apache-2.0"
repository = "https://github.com/SergioBenitez/Devise"

[dependencies]
quote-next = "1.0.0-rc1"
proc-macro2-next = { version = "1.0.0-rc1", features = ["nightly"] }
syn-next = { version = "1.0.0-rc2", features = ["full", "extra-traits"] }
bitflags = "1.0"
