[package]
name = "uri_display"
version = "0.0.0"
authors = ["Sergio Benitez <sb@sergio.bz>"]
publish = false

[lib]
proc-macro = true

[[bin]]
name = "main"
path = "src/main.rs"
doc = false

[dependencies]
quote = "1.0"
devise = { path = "../../lib" }
